[2024-03-20T04:38:45.809+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_and_Cassandra.insert_dummy_data manual__2024-03-20T04:38:40.607737+00:00 [queued]>
[2024-03-20T04:38:45.817+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_and_Cassandra.insert_dummy_data manual__2024-03-20T04:38:40.607737+00:00 [queued]>
[2024-03-20T04:38:45.817+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-20T04:38:45.828+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): insert_dummy_data> on 2024-03-20 04:38:40.607737+00:00
[2024-03-20T04:38:45.839+0000] {standard_task_runner.py:60} INFO - Started process 6955 to run task
[2024-03-20T04:38:45.844+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Airflow_and_Cassandra', 'insert_dummy_data', 'manual__2024-03-20T04:38:40.607737+00:00', '--job-id', '365', '--raw', '--subdir', 'DAGS_FOLDER/insert_cassandra.py', '--cfg-path', '/tmp/tmpxblsvb69']
[2024-03-20T04:38:45.845+0000] {standard_task_runner.py:88} INFO - Job 365: Subtask insert_dummy_data
[2024-03-20T04:38:46.493+0000] {task_command.py:423} INFO - Running <TaskInstance: Airflow_and_Cassandra.insert_dummy_data manual__2024-03-20T04:38:40.607737+00:00 [running]> on host 52dfb58d56f6
[2024-03-20T04:38:47.282+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Airflow_and_Cassandra' AIRFLOW_CTX_TASK_ID='insert_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-20T04:38:40.607737+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-20T04:38:40.607737+00:00'
[2024-03-20T04:38:47.342+0000] {base.py:83} INFO - Using connection ID 'cassandra_default' for task execution.
[2024-03-20T04:38:47.351+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/apache/cassandra/hooks/cassandra.py:120: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2024-03-20T04:38:47.388+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 66 to 65 for 172.18.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-03-20T04:38:47.395+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 65 to 5 for 172.18.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-03-20T04:38:47.405+0000] {asyncorereactor.py:455} WARNING - An authentication challenge was not sent, this is suspicious because the driver expects authentication (configured authenticator = PlainTextAuthenticator)
[2024-03-20T04:38:47.535+0000] {asyncorereactor.py:455} WARNING - An authentication challenge was not sent, this is suspicious because the driver expects authentication (configured authenticator = PlainTextAuthenticator)
[2024-03-20T04:38:47.547+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/insert_cassandra.py", line 46, in insert_dummy_data_into_cassandra_db
    session.execute(query, (uuid4(), data["date"], data["state"], data["gini"], data["poverty"], data["income_mean"], data["income_median"], data["expenditure_mean"]))
  File "cassandra/cluster.py", line 2677, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4956, in cassandra.cluster.ResponseFuture.result
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid FLOAT constant (0.36646) for "gini" of type text"
[2024-03-20T04:38:47.578+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Airflow_and_Cassandra, task_id=insert_dummy_data, execution_date=20240320T043840, start_date=20240320T043845, end_date=20240320T043847
[2024-03-20T04:38:47.646+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 365 for task insert_dummy_data (Error from server: code=2200 [Invalid query] message="Invalid FLOAT constant (0.36646) for "gini" of type text"; 6955)
[2024-03-20T04:38:47.777+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-20T04:38:47.876+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
