[2024-03-19T16:14:50.623+0000] {processor.py:161} INFO - Started process (PID=31259) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:14:50.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:14:50.634+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:14:50.633+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:14:50.649+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:14:50.647+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:14:50.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:14:50.688+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.071 seconds
[2024-03-19T16:15:21.023+0000] {processor.py:161} INFO - Started process (PID=31320) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:15:21.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:15:21.055+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:15:21.054+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:15:21.090+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:15:21.080+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:15:21.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:15:21.160+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.152 seconds
[2024-03-19T16:15:51.609+0000] {processor.py:161} INFO - Started process (PID=31400) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:15:51.621+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:15:51.634+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:15:51.633+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:15:51.698+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:15:51.688+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:15:51.707+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:15:52.412+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.842 seconds
[2024-03-19T16:16:23.203+0000] {processor.py:161} INFO - Started process (PID=31468) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:16:23.207+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:16:23.220+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:16:23.219+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:16:23.234+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:16:23.232+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:16:23.235+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:16:23.286+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.102 seconds
[2024-03-19T16:16:53.651+0000] {processor.py:161} INFO - Started process (PID=31541) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:16:53.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:16:53.665+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:16:53.663+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:16:53.693+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:16:53.686+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:16:53.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:16:53.792+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.170 seconds
[2024-03-19T16:17:24.118+0000] {processor.py:161} INFO - Started process (PID=31594) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:17:24.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:17:24.126+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:17:24.125+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:17:24.173+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:17:24.159+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:17:24.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:17:24.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.112 seconds
[2024-03-19T16:17:54.754+0000] {processor.py:161} INFO - Started process (PID=31664) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:17:54.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:17:54.770+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:17:54.769+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:17:54.788+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:17:54.785+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:17:54.789+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:17:54.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.131 seconds
[2024-03-19T16:18:25.412+0000] {processor.py:161} INFO - Started process (PID=31745) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:18:25.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:18:25.465+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:18:25.465+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:18:25.509+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:18:25.498+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:18:25.524+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:18:25.593+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.232 seconds
[2024-03-19T16:18:55.848+0000] {processor.py:161} INFO - Started process (PID=31824) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:18:55.851+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:18:55.891+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:18:55.880+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:18:55.946+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:18:55.940+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:18:55.950+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:18:56.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.201 seconds
[2024-03-19T16:19:26.883+0000] {processor.py:161} INFO - Started process (PID=31873) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:19:26.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:19:26.955+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:19:26.953+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:19:27.088+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:19:27.065+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:19:27.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:19:27.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.986 seconds
[2024-03-19T16:19:58.542+0000] {processor.py:161} INFO - Started process (PID=31931) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:19:58.549+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:19:58.565+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:19:58.563+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:19:58.605+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:19:58.599+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:19:58.608+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:19:58.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.196 seconds
[2024-03-19T16:20:29.435+0000] {processor.py:161} INFO - Started process (PID=31969) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:20:29.449+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:20:29.547+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:20:29.541+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:20:29.701+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:20:29.682+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:20:29.707+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:20:30.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.718 seconds
[2024-03-19T16:21:01.925+0000] {processor.py:161} INFO - Started process (PID=31986) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:21:01.941+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:21:02.028+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:21:02.000+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:21:02.274+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:21:02.253+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:21:02.298+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:21:02.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.950 seconds
[2024-03-19T16:21:33.939+0000] {processor.py:161} INFO - Started process (PID=32007) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:21:33.948+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:21:34.011+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:21:34.007+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:21:34.124+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:21:34.112+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:21:34.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:21:34.587+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.713 seconds
[2024-03-19T16:22:06.197+0000] {processor.py:161} INFO - Started process (PID=32019) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:22:06.214+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:22:06.272+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:22:06.269+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:22:06.449+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:22:06.400+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:22:06.459+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:22:07.060+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.910 seconds
[2024-03-19T16:22:39.159+0000] {processor.py:161} INFO - Started process (PID=32038) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:22:39.228+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:22:39.322+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:22:39.312+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:22:39.650+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:22:39.624+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:22:39.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:22:40.048+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 1.058 seconds
[2024-03-19T16:25:43.375+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:25:43.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:25:43.399+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:25:43.395+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:25:43.444+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:25:43.432+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:25:43.450+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:25:43.662+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.320 seconds
[2024-03-19T16:26:15.188+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:26:15.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:26:15.386+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:26:15.361+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:26:15.842+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:26:15.789+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:26:15.854+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:26:16.454+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 1.327 seconds
[2024-03-19T16:26:47.780+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:26:47.784+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:26:47.809+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:26:47.807+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:26:47.852+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:26:47.841+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:26:47.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:26:48.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.251 seconds
[2024-03-19T16:27:19.118+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:27:19.195+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:27:19.329+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:27:19.294+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:27:19.632+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:27:19.604+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:27:19.635+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:27:20.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 1.172 seconds
[2024-03-19T16:27:51.337+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:27:51.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:27:51.511+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:27:51.497+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:27:51.686+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:27:51.679+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:27:51.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:27:51.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.656 seconds
[2024-03-19T16:28:23.219+0000] {processor.py:161} INFO - Started process (PID=115) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:28:23.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:28:23.276+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:28:23.274+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:28:23.709+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:28:23.654+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:28:23.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:28:24.013+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.882 seconds
[2024-03-19T16:28:55.866+0000] {processor.py:161} INFO - Started process (PID=123) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:28:55.921+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:28:55.996+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:28:55.981+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:28:56.213+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:28:56.196+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:28:56.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:28:56.411+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.665 seconds
[2024-03-19T16:29:27.542+0000] {processor.py:161} INFO - Started process (PID=131) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:29:27.574+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:29:27.626+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:29:27.624+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:29:27.717+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:29:27.704+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:29:27.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:29:27.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.377 seconds
[2024-03-19T16:29:59.677+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:29:59.683+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:29:59.756+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:29:59.718+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:29:59.953+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:29:59.940+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:29:59.970+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:30:00.793+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 1.138 seconds
[2024-03-19T16:30:32.630+0000] {processor.py:161} INFO - Started process (PID=156) to work on /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:30:32.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_data_to_cassandra.py for tasks to queue
[2024-03-19T16:30:32.696+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:30:32.691+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:30:32.839+0000] {logging_mixin.py:188} INFO - [2024-03-19T16:30:32.808+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_data_to_cassandra.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/api_data_to_cassandra.py", line 6, in <module>
    from airflow.providers.apache.cassandra.hooks.cassandra import CassandraHook
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-03-19T16:30:32.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_data_to_cassandra.py
[2024-03-19T16:30:33.444+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_data_to_cassandra.py took 0.953 seconds
