[2024-03-19T19:40:40.909+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_and_Cassandra.insert_dummy_data manual__2024-03-19T19:40:39.572861+00:00 [queued]>
[2024-03-19T19:40:40.921+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_and_Cassandra.insert_dummy_data manual__2024-03-19T19:40:39.572861+00:00 [queued]>
[2024-03-19T19:40:40.921+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-19T19:40:40.933+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): insert_dummy_data> on 2024-03-19 19:40:39.572861+00:00
[2024-03-19T19:40:40.941+0000] {standard_task_runner.py:60} INFO - Started process 568 to run task
[2024-03-19T19:40:40.946+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Airflow_and_Cassandra', 'insert_dummy_data', 'manual__2024-03-19T19:40:39.572861+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/insert_cassandra.py', '--cfg-path', '/tmp/tmpl9k10v0x']
[2024-03-19T19:40:40.948+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask insert_dummy_data
[2024-03-19T19:40:41.006+0000] {task_command.py:423} INFO - Running <TaskInstance: Airflow_and_Cassandra.insert_dummy_data manual__2024-03-19T19:40:39.572861+00:00 [running]> on host 52dfb58d56f6
[2024-03-19T19:40:41.071+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Airflow_and_Cassandra' AIRFLOW_CTX_TASK_ID='insert_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T19:40:39.572861+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-19T19:40:39.572861+00:00'
[2024-03-19T19:40:41.082+0000] {base.py:83} INFO - Using connection ID 'cassandra_default' for task execution.
[2024-03-19T19:40:41.085+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/apache/cassandra/hooks/cassandra.py:120: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2024-03-19T19:40:41.089+0000] {cassandra.py:128} WARNING - [control connection] Error connecting to 127.0.0.1:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3577, in cassandra.cluster.ControlConnection._reconnect_internal
  File "cassandra/cluster.py", line 3599, in cassandra.cluster.ControlConnection._try_connect
  File "cassandra/cluster.py", line 1670, in cassandra.cluster.Cluster.connection_factory
  File "cassandra/connection.py", line 846, in cassandra.connection.Connection.factory
  File "/home/airflow/.local/lib/python3.8/site-packages/cassandra/io/asyncorereactor.py", line 354, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 951, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused
[2024-03-19T19:40:41.092+0000] {cassandra.py:128} ERROR - Control connection failed to connect, shutting down Cluster:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 1740, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 3543, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3588, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
[2024-03-19T19:40:41.093+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/insert_cassandra.py", line 16, in insert_dummy_data_into_cassandra_db
    session = hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 128, in get_conn
    self.session = self.cluster.connect(self.keyspace)
  File "cassandra/cluster.py", line 1717, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1753, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1740, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 3543, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3588, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
[2024-03-19T19:40:41.122+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Airflow_and_Cassandra, task_id=insert_dummy_data, execution_date=20240319T194039, start_date=20240319T194040, end_date=20240319T194041
[2024-03-19T19:40:41.132+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 30 for task insert_dummy_data (('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")}); 568)
[2024-03-19T19:40:41.163+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-19T19:40:41.182+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
