[2024-03-20T04:25:49.623+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_and_Cassandra.get_rest_api_data manual__2024-03-20T04:25:46.859938+00:00 [queued]>
[2024-03-20T04:25:49.634+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_and_Cassandra.get_rest_api_data manual__2024-03-20T04:25:46.859938+00:00 [queued]>
[2024-03-20T04:25:49.635+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-20T04:25:49.649+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_rest_api_data> on 2024-03-20 04:25:46.859938+00:00
[2024-03-20T04:25:49.686+0000] {standard_task_runner.py:60} INFO - Started process 6738 to run task
[2024-03-20T04:25:49.697+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Airflow_and_Cassandra', 'get_rest_api_data', 'manual__2024-03-20T04:25:46.859938+00:00', '--job-id', '355', '--raw', '--subdir', 'DAGS_FOLDER/insert_cassandra.py', '--cfg-path', '/tmp/tmpodrdn0x2']
[2024-03-20T04:25:49.701+0000] {standard_task_runner.py:88} INFO - Job 355: Subtask get_rest_api_data
[2024-03-20T04:25:49.940+0000] {task_command.py:423} INFO - Running <TaskInstance: Airflow_and_Cassandra.get_rest_api_data manual__2024-03-20T04:25:46.859938+00:00 [running]> on host 52dfb58d56f6
[2024-03-20T04:25:50.218+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Airflow_and_Cassandra' AIRFLOW_CTX_TASK_ID='get_rest_api_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-20T04:25:46.859938+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-20T04:25:46.859938+00:00'
[2024-03-20T04:25:50.963+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/insert_cassandra.py", line 23, in get_rest_api_data
    json_data = json.loads(response_json)
  File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list
[2024-03-20T04:25:51.350+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Airflow_and_Cassandra, task_id=get_rest_api_data, execution_date=20240320T042546, start_date=20240320T042549, end_date=20240320T042551
[2024-03-20T04:25:51.512+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 355 for task get_rest_api_data (the JSON object must be str, bytes or bytearray, not list; 6738)
[2024-03-20T04:25:51.813+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-20T04:25:52.307+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
